const swaggerAutogen = require('swagger-autogen')();

require('dotenv').config();

const doc = {
    info: {
        title: 'CRUD API - Products and Users',
        description: 'API for managing products and users',
        version: '1.0.0'
    },
    host: process.env.SWAGGER_HOST || 'localhost:3000',
    schemes: [process.env.NODE_ENV === 'production' ? 'https' : 'http'],
    basePath: '/',
    produces: ['application/json'],
    consumes: ['application/json'],
    components: {
        securitySchemes: {
            sessionAuth: {
                type: 'apiKey',
                in: 'cookie',
                name: 'connect.sid',
                description: 'Session cookie autogenerated by express-session'
            }
        }
    },
    security: [{ sessionAuth: [] }]
};

const outputFile = './swagger.json';
const endpointsFiles = ['./routes/product.js', './routes/users.js', './routes/index.js'];

// Generate the swagger.json file
swaggerAutogen(outputFile, endpointsFiles, doc);
